class LoanSimulateHomeEquity < SitePrism::Page
	element :loan_amount, "input[name='valor-emprestimo']"
  element :loan_amount_double_check, "input[name='loan-amount']"
  element :financing_time_months, "select[name='financing-time-months']"
  element :customer_full_name, "input[name='customer-full-name']"
  element :customer_cpf, "input[name='customer-cpf']"
	element :customer_birth_date, "input[name='customer-birth-date']"
  element :lead_family_monthly_income, "input[name='lead-family-monthly-income']"
  element :customer_phone, "input[name='customer-phone']"
  element :lead_purpose, "select[name='lead-purpose']"
  element :customer_email, "input[name='customer-email']"
  element :customer_password, "input[name='customer-password']"
  element :customer_password_confirmation, "input[name='customer-password-confirmation']"
  element :lead_real_estate_address, "input[name='lead-real-estate-address']"
  element :lead_real_estate_number, "input[name='lead-real-estate-number']"
  element :lead_real_estate_complement, "input[name='lead-real-estate-complement']"
  element :lead_real_estate_zip_code, "input[name='lead-real-estate-zip-code']"
  element :lead_real_estate_neighborhood, "input[name='lead-real-estate-neighborhood']"
  element :lead_real_estate_city, "input[name='lead-real-estate-city']"
  element :lead_real_estate_state, "select[name='lead-real-estate-state']"
  element :lead_real_estate_country, "input[name='lead-real-estate-country']"  
  element :lead_real_estate_value, "input[name='lead-real-estate-value']"  
  element :lead_real_estate_type, "select[name='lead-real-estate-type']" 
end

